#include "Scene/ProjectActorFactory.h"

#include "Library/Fluid/FlowMapParts.h"
#include "Library/Fluid/RippleFixMapParts.h"
#include "Library/Fluid/RippleGeneratePoint.h"
#include "Library/Fog/FogRequester.h"
#include "Library/LiveActor/CreateActorFunction.h"
#include "Library/MapObj/BackHideParts.h"
#include "Library/MapObj/ClockMapParts.h"
#include "Library/MapObj/ConveyerMapParts.h"
#include "Library/MapObj/FallMapParts.h"
#include "Library/MapObj/FixMapParts.h"
#include "Library/MapObj/FloaterMapParts.h"
#include "Library/MapObj/GateMapParts.h"
#include "Library/MapObj/KeyMoveMapParts.h"
#include "Library/MapObj/KeyMoveMapPartsGenerator.h"
#include "Library/MapObj/OneMeshFixMapParts.h"
#include "Library/MapObj/RailMoveMapParts.h"
#include "Library/MapObj/RollingCubeMapParts.h"
#include "Library/MapObj/RotateMapParts.h"
#include "Library/MapObj/SeesawMapParts.h"
#include "Library/MapObj/SlideMapParts.h"
#include "Library/MapObj/SubActorLodMapParts.h"
#include "Library/MapObj/SurfMapParts.h"
#include "Library/MapObj/SwingMapParts.h"
#include "Library/MapObj/SwitchDitherMapParts.h"
#include "Library/MapObj/SwitchOpenMapParts.h"
#include "Library/MapObj/VisibleSwitchMapParts.h"
#include "Library/MapObj/WheelMapParts.h"
#include "Library/MapObj/WobbleMapParts.h"
#include "Library/Obj/AllDeadWatcher.h"
#include "Library/Obj/BgmPlayObj.h"
#include "Library/Obj/CameraRailHolder.h"
#include "Library/Obj/CameraWatchPoint.h"
#include "Library/Obj/EffectObj.h"
#include "Library/Obj/EffectObjCameraEmit.h"
#include "Library/Obj/EffectObjFollowCamera.h"
#include "Library/Obj/EffectObjFollowCameraLimit.h"
#include "Library/Obj/EffectObjInterval.h"
#include "Library/Obj/KeyMoveCameraObj.h"
#include "Library/Obj/LightningController.h"
#include "Library/Obj/SeBarrierObj.h"
#include "Library/Obj/SePlayObj.h"
#include "Library/Obj/SePlayRail.h"
#include "Library/Obj/Sky.h"
#include "Library/Obj/SwitchKeepOnWatcher.h"
#include "Library/Obj/WaterAreaMoveModel.h"
#include "Library/Play/Camera/EntranceCameraStartObj.h"
#include "Library/PostProcessing/OccludedEffectRequester.h"
#include "Library/Shader/DeferredRendering/AtmosScatterRequester.h"

#include "Audio/SePlayObjWithSave.h"
#include "Audio/ShopBgmPlayer.h"
#include "Boss/BarrierField.h"
#include "Boss/BombTail/BombTail.h"
#include "Boss/BossForest/BossForest.h"
#include "Boss/BossForest/BossForestBlock.h"
#include "Boss/BossForest/BossForestWander.h"
#include "Boss/BossKnuckle/BossKnuckle.h"
#include "Boss/BossKnuckle/BossKnuckleCounterGround.h"
#include "Boss/BossRaid/BossRaid.h"
#include "Boss/BossRaid/BossRaidNpc.h"
#include "Boss/BossRaid/BossRaidRivet.h"
#include "Boss/Breeda/Breeda.h"
#include "Boss/CapThrower/CapThrower.h"
#include "Boss/FireBlower/FireBlower.h"
#include "Boss/GiantWanderBoss/GiantWanderBoss.h"
#include "Boss/GolemClimb/GolemClimb.h"
#include "Boss/Koopa/Koopa.h"
#include "Boss/Koopa/KoopaCapPlayer.h"
#include "Boss/Koopa/KoopaChurch.h"
#include "Boss/Koopa/KoopaLv1.h"
#include "Boss/Mofumofu/Mofumofu.h"
#include "Boss/Mofumofu/MofumofuScrap.h"
#include "Boss/MultiGateKeeper/MultiGateKeeperBonfire.h"
#include "Boss/MultiGateKeeper/MultiGateKeeperWatcher.h"
#include "Boss/Objex/Objex.h"
#include "Boss/SmallWanderBoss/SmallWanderBoss.h"
#include "Boss/Stacker/Stacker.h"
#include "Boss/Stacker/StackerCapWorldCtrl.h"
#include "Camera/EventKeyMoveCameraObjNoDemo.h"
#include "Camera/EventKeyMoveCameraObjWithDemo.h"
#include "Camera/ScenarioStartCamera.h"
#include "Demo/DemoActorCapManHero.h"
#include "Demo/DemoActorCapManHeroine.h"
#include "Demo/DemoActorHack.h"
#include "Demo/DemoActorKoopaShip.h"
#include "Demo/DemoActorPeach.h"
#include "Demo/DemoActorShineTower.h"
#include "Demo/DemoPeachWedding.h"
#include "Demo/DemoPlayer.h"
#include "Demo/DemoPlayerCap.h"
#include "Demo/OpeningStageStartDemo.h"
#include "Demo/StageTalkDemoNpcCap.h"
#include "Enemy/Bubble.h"
#include "Enemy/CatchBomb.h"
#include "Enemy/DonkeyKong2D.h"
#include "Enemy/Gamane.h"
#include "Enemy/GunetterSpin.h"
#include "Enemy/HammerBros2D.h"
#include "Enemy/Hosui.h"
#include "Enemy/Joku.h"
#include "Enemy/JugemFishing.h"
#include "Enemy/Kakku.h"
#include "Enemy/KaronWing.h"
#include "Enemy/KillerLauncher.h"
#include "Enemy/KillerLauncherDot.h"
#include "Enemy/Kuribo2D.h"
#include "Enemy/KuriboGenerator2D.h"
#include "Enemy/KuriboHack.h"
#include "Enemy/KuriboMini.h"
#include "Enemy/KuriboWing.h"
#include "Enemy/LongGenerator.h"
#include "Enemy/Megane.h"
#include "Enemy/Mummy.h"
#include "Enemy/MummyGenerator.h"
#include "Enemy/Nokonoko2D.h"
#include "Enemy/PackunFire.h"
#include "Enemy/Pecho.h"
#include "Enemy/PopnGenerator.h"
#include "Enemy/Pukupuku.h"
#include "Enemy/ReflectBombGenerator.h"
#include "Enemy/Senobi.h"
#include "Enemy/SenobiGeneratePoint.h"
#include "Enemy/TRex.h"
#include "Enemy/Tank.h"
#include "Enemy/TankReviveCtrl.h"
#include "Enemy/Togezo.h"
#include "Enemy/Togezo2D.h"
#include "Enemy/Utsubo.h"
#include "Enemy/UtsuboWatcher.h"
#include "Enemy/Wanwan.h"
#include "Enemy/WanwanHole.h"
#include "Item/Coin.h"
#include "Item/Coin2D.h"
#include "Item/Coin2DCityDirector.h"
#include "Item/CoinBlow.h"
#include "Item/CoinChameleon.h"
#include "Item/CoinCirclePlacement.h"
#include "Item/CoinCollect.h"
#include "Item/CoinCollect2D.h"
#include "Item/CoinLead.h"
#include "Item/CoinRail.h"
#include "Item/CoinRing.h"
#include "Item/CoinStackGroup.h"
#include "Item/LifeMaxUpItem.h"
#include "Item/LifeMaxUpItem2D.h"
#include "Item/LifeUpItem.h"
#include "Item/LifeUpItem2D.h"
#include "Item/Shine.h"
#include "Item/ShineChipWatcher.h"
#include "Item/ShineFukankunWatchObj.h"
#include "Item/YoshiFruit.h"
#include "Item/YoshiFruitShineHolder.h"
#include "MapObj/AirBubble.h"
#include "MapObj/AirBubbleGenerator.h"
#include "MapObj/AirCurrent.h"
#include "MapObj/AllDeadWatcherWithShine.h"
#include "MapObj/AnagramAlphabet.h"
#include "MapObj/Barrel2D.h"
#include "MapObj/BarrelGenerator2D.h"
#include "MapObj/BazookaElectric.h"
#include "MapObj/BendLeafTree.h"
#include "MapObj/BlockBrick.h"
#include "MapObj/BlockBrick2D.h"
#include "MapObj/BlockBrickBig2D.h"
#include "MapObj/BlockEmpty.h"
#include "MapObj/BlockEmpty2D.h"
#include "MapObj/BlockHard.h"
#include "MapObj/BlockQuestion.h"
#include "MapObj/BlockQuestion2D.h"
#include "MapObj/BlockTransparent.h"
#include "MapObj/BlockTransparent2D.h"
#include "MapObj/BlowObj.h"
#include "MapObj/BossKnuckleFix.h"
#include "MapObj/BreakMapParts.h"
#include "MapObj/BreakablePole.h"
#include "MapObj/BubbleLauncher.h"
#include "MapObj/Cactus.h"
#include "MapObj/CactusMini.h"
#include "MapObj/CageShineWatcher.h"
#include "MapObj/CageSwitch.h"
#include "MapObj/CameraDemoGateMapParts.h"
#include "MapObj/CameraDemoKeyMoveMapParts.h"
#include "MapObj/CameraSub.h"
#include "MapObj/Candlestand.h"
#include "MapObj/CandlestandBgmDirector.h"
#include "MapObj/CandlestandInitializer.h"
#include "MapObj/CandlestandSaveWatcher.h"
#include "MapObj/CandlestandWatcher.h"
#include "MapObj/CapAccelerator.h"
#include "MapObj/CapAppearMapParts.h"
#include "MapObj/CapBeamer.h"
#include "MapObj/CapBomb.h"
#include "MapObj/CapCatapult.h"
#include "MapObj/CapFlower.h"
#include "MapObj/CapFlowerGroup.h"
#include "MapObj/CapHanger.h"
#include "MapObj/CapMessageAfterInformation.h"
#include "MapObj/CapMessagePlacement.h"
#include "MapObj/CapRack.h"
#include "MapObj/CapRailMover.h"
#include "MapObj/CapRotateMapParts.h"
#include "MapObj/CapSwitch.h"
#include "MapObj/CapSwitchTimer.h"
#include "MapObj/CapTrampoline.h"
#include "MapObj/Car.h"
#include "MapObj/CarWatcher.h"
#include "MapObj/CardboardBox.h"
#include "MapObj/Chair.h"
#include "MapObj/CheckpointFlag.h"
#include "MapObj/ChurchDoor.h"
#include "MapObj/CityBuilding.h"
#include "MapObj/CitySign.h"
#include "MapObj/CitySignal.h"
#include "MapObj/CityStreetlight.h"
#include "MapObj/CityWorldSign.h"
#include "MapObj/CityWorldUndergroundMachine.h"
#include "MapObj/Closet.h"
#include "MapObj/CloudStep.h"
#include "MapObj/CoinCollectHintObj.h"
#include "MapObj/CollapseSandHill.h"
#include "MapObj/CollectBgmSpeaker.h"
#include "MapObj/CollectionList.h"
#include "MapObj/CrystalBreakable.h"
#include "MapObj/DamageBallGenerator.h"
#include "MapObj/DelaySwitch.h"
#include "MapObj/DemoChangeEffectObj.h"
#include "MapObj/DemoWorldMoveHomeBackGround.h"
#include "MapObj/DigPoint.h"
#include "MapObj/Dokan.h"
#include "MapObj/DokanKoopa.h"
#include "MapObj/DokanMaze.h"
#include "MapObj/DokanMazeDirector.h"
#include "MapObj/DokanStageChange.h"
#include "MapObj/DoorAreaChange.h"
#include "MapObj/DoorAreaChangeCap.h"
#include "MapObj/DoorCity.h"
#include "MapObj/DoorSnow.h"
#include "MapObj/DoorWarp.h"
#include "MapObj/DoorWarpStageChange.h"
#include "MapObj/Doshi.h"
#include "MapObj/EchoBlockMapParts.h"
#include "MapObj/EffectObjAlpha.h"
#include "MapObj/EffectObjQualityChange.h"
#include "MapObj/ElectricWire/ElectricWire.h"
#include "MapObj/ElectricWireKoopa.h"
#include "MapObj/Fastener.h"
#include "MapObj/FastenerObj.h"
#include "MapObj/FireDrum2D.h"
#include "MapObj/FireHydrant.h"
#include "MapObj/FireSwitch.h"
#include "MapObj/FishingFish.h"
#include "MapObj/FixMapParts2D.h"
#include "MapObj/FixMapPartsAppearKillAsync.h"
#include "MapObj/FixMapPartsBgmChangeAction.h"
#include "MapObj/FixMapPartsCapHanger.h"
#include "MapObj/FixMapPartsDitherAppear.h"
#include "MapObj/FixMapPartsForceSafetyPoint.h"
#include "MapObj/FixMapPartsFukankunZoomCapMessage.h"
#include "MapObj/FixMapPartsScenarioAction.h"
#include "MapObj/ForestWorldEnergyStand.h"
#include "MapObj/ForestWorldFlowerCtrl.h"
#include "MapObj/FrailBox.h"
#include "MapObj/Fukankun.h"
#include "MapObj/FukankunZoomCapMessageSun.h"
#include "MapObj/GoalMark.h"
#include "MapObj/GotogotonGoal.h"
#include "MapObj/GrowFlowerCoin.h"
#include "MapObj/GrowFlowerWatcher.h"
#include "MapObj/GrowPlantGrowPlace.h"
#include "MapObj/GrowPlantStartStage.h"
#include "MapObj/GrowPlantWatcher.h"
#include "MapObj/HackCar.h"
#include "MapObj/HackFork.h"
#include "MapObj/HackMapParts.h"
#include "MapObj/HintPhoto.h"
#include "MapObj/HipDropMoveLift.h"
#include "MapObj/HipDropRepairParts.h"
#include "MapObj/HipDropSwitch.h"
#include "MapObj/HipDropSwitchTimer.h"
#include "MapObj/HipDropTile.h"
#include "MapObj/HipDropTransformPartsWatcher.h"
#include "MapObj/HomeBed.h"
#include "MapObj/HomeChair.h"
#include "MapObj/HomeInside.h"
#include "MapObj/IcicleFall.h"
#include "MapObj/IndicatorDirector.h"
#include "MapObj/KickStone.h"
#include "MapObj/KinokoUfo.h"
#include "MapObj/KoopaShip.h"
#include "MapObj/KuriboTowerSwitch.h"
#include "MapObj/LavaFryingPan.h"
#include "MapObj/LavaPan.h"
#include "MapObj/LavaStewVeget.h"
#include "MapObj/LavaWave.h"
#include "MapObj/MapPartsRoulette.h"
#include "MapObj/MarchingCubeBlock.h"
#include "MapObj/MeganeKeyMoveMapParts.h"
#include "MapObj/MeganeLiftExLift.h"
#include "MapObj/MeganeMapParts.h"
#include "MapObj/MoonBasementBreakParts.h"
#include "MapObj/MoonBasementFallObjDecoration.h"
#include "MapObj/MoonBasementFinalGate.h"
#include "MapObj/MoonBasementFloor.h"
#include "MapObj/MoonBasementMeteorAreaObj.h"
#include "MapObj/MoonBasementMeteorPointObj.h"
#include "MapObj/MoonBasementPillar.h"
#include "MapObj/MoonBasementRock.h"
#include "MapObj/MoonBasementSlideObj.h"
#include "MapObj/MoonRock.h"
#include "MapObj/MoonWorldBell.h"
#include "MapObj/MoonWorldCaptureParadeLift.h"
#include "MapObj/Motorcycle.h"
#include "MapObj/MotorcycleParkingLot.h"
#include "MapObj/MoviePlayerMapParts.h"
#include "MapObj/NeedleTrap.h"
#include "MapObj/NoteObj.h"
#include "MapObj/NoteObj2D.h"
#include "MapObj/NoteObjDirector.h"
#include "MapObj/OceanWaveActor.h"
#include "MapObj/PadRumblePoint.h"
#include "MapObj/PaintObj.h"
#include "MapObj/PeachCastleCap.h"
#include "MapObj/PeachWorldGate.h"
#include "MapObj/PeachWorldMoatWater.h"
#include "MapObj/PeachWorldTree.h"
#include "MapObj/Pen.h"
#include "MapObj/PictureStageChange.h"
#include "MapObj/PillarKeyMoveParts.h"
#include "MapObj/PillarSwitchOpenMapParts.h"
#include "MapObj/PlayGuideBoard.h"
#include "MapObj/PlayRecorder.h"
#include "MapObj/PlayerMotionObserver.h"
#include "MapObj/PlayerStartObj.h"
#include "MapObj/PlayerSubjectiveWatchCheckObj.h"
#include "MapObj/PoleClimbParts.h"
#include "MapObj/PoleGrabCeil.h"
#include "MapObj/PosterWatcher.h"
#include "MapObj/ProjectGraphicsObjShadowMaskCube.h"
#include "MapObj/ProjectRaceCheckPoint.h"
#include "MapObj/PulseSwitch.h"
#include "MapObj/Pyramid.h"
#include "MapObj/QuestObj.h"
#include "MapObj/RaceWatcher.h"
#include "MapObj/RadiConRaceWatcher.h"
#include "MapObj/RadioCassette.h"
#include "MapObj/Radish.h"
#include "MapObj/RailCollision.h"
#include "MapObj/RailDrawer.h"
#include "MapObj/ReactionMapParts.h"
#include "MapObj/ReactionObject.h"
#include "MapObj/ReactionObjectCarBreakable.h"
#include "MapObj/ReactionObjectPoster.h"
#include "MapObj/ReactionObjectSkyRhythm.h"
#include "MapObj/RhythmSpotlight.h"
#include "MapObj/RiseMapParts.h"
#include "MapObj/RiseMapPartsHolder.h"
#include "MapObj/RocketFlower.h"
#include "MapObj/RotateTarget.h"
#include "MapObj/RouletteSwitch.h"
#include "MapObj/RouteGuideRail.h"
#include "MapObj/SandGeyser.h"
#include "MapObj/SandWorldHomeLift.h"
#include "MapObj/SaucePan.h"
#include "MapObj/SaveFlagCheckObj.h"
#include "MapObj/SenobiMoveMapParts.h"
#include "MapObj/SenobiMoveMapPartsConnector.h"
#include "MapObj/SequentialSwitch.h"
#include "MapObj/ShineTowerRocket.h"
#include "MapObj/ShopMark.h"
#include "MapObj/SignBoard.h"
#include "MapObj/SignBoardDanger.h"
#include "MapObj/SignBoardLayoutTexture.h"
#include "MapObj/SkyFukankunZoomCapMessage.h"
#include "MapObj/SkyWorldCloud.h"
#include "MapObj/SkyWorldKoopaFire.h"
#include "MapObj/SkyWorldMiddleViewCloud.h"
#include "MapObj/SneakingMan.h"
#include "MapObj/SnowVolume.h"
#include "MapObj/SnowVolumeEraser.h"
#include "MapObj/SnowWorldBigIcicle.h"
#include "MapObj/SnowWorldSequenceFlagCheckObj.h"
#include "MapObj/Souvenir.h"
#include "MapObj/SouvenirDirector.h"
#include "MapObj/Special2KeyMoveLift.h"
#include "MapObj/SphinxTaxiWatcher.h"
#include "MapObj/StageSwitchSelector.h"
#include "MapObj/Stake.h"
#include "MapObj/Statue.h"
#include "MapObj/StatueSnapMark.h"
#include "MapObj/SubActorLodFixPartsScenarioAction.h"
#include "MapObj/SwitchAnd.h"
#include "MapObj/TRexScrollBreakMapParts.h"
#include "MapObj/TalkMessageInfoPointSaveObj.h"
#include "MapObj/TalkPoint.h"
#include "MapObj/TextureReplaceScreen.h"
#include "MapObj/TrampleBush.h"
#include "MapObj/TrampleSwitch.h"
#include "MapObj/TrampleSwitchTimer.h"
#include "MapObj/TransparentWall.h"
#include "MapObj/TreasureBox.h"
#include "MapObj/TreasureBoxKey.h"
#include "MapObj/TreasureBoxSequentialDirector.h"
#include "MapObj/TsukkunHole.h"
#include "MapObj/TwistChainList.h"
#include "MapObj/VolleyballBase.h"
#include "MapObj/VolleyballNet.h"
#include "MapObj/WaterRoad.h"
#include "MapObj/WaterfallWorldBigBreakableWall.h"
#include "MapObj/WaterfallWorldFallDownBridge.h"
#include "MapObj/WaterfallWorldWaterfall.h"
#include "MapObj/WaveSurfMapParts.h"
#include "MapObj/WeightSwitch.h"
#include "MapObj/WheelWaveSurfParts.h"
#include "MapObj/WindBlowMapParts.h"
#include "MapObj/WindBlowPuzzle.h"
#include "MapObj/WorldMapEarth.h"
#include "MapObj/WorldWarpHole.h"
#include "Npc/AmiiboHelpNpc.h"
#include "Npc/AmiiboNpc.h"
#include "Npc/Bird.h"
#include "Npc/BirdPlayerGlideCtrl.h"
#include "Npc/CollectAnimalWatcher.h"
#include "Npc/EffectObjNpcManFar.h"
#include "Npc/FlyObject.h"
#include "Npc/ForestManSeed.h"
#include "Npc/Frog.h"
#include "Npc/FukuwaraiWatcher.h"
#include "Npc/HelpNpc.h"
#include "Npc/JumpingRopeNpc.h"
#include "Npc/KuriboGirl.h"
#include "Npc/MoveHomeNpc.h"
#include "Npc/PaulineAtCeremony.h"
#include "Npc/PaulineAudience.h"
#include "Npc/PochiHintPhoto.h"
#include "Npc/Poetter.h"
#include "Npc/RabbitGraph.h"
#include "Npc/RaceAudienceNpc.h"
#include "Npc/RaceManGoal.h"
#include "Npc/RaceManRace.h"
#include "Npc/RadiconNpc.h"
#include "Npc/RunAwayNpc.h"
#include "Npc/SessionMayorNpc.h"
#include "Npc/Shibaken.h"
#include "Npc/SphinxQuiz.h"
#include "Npc/Squirrel.h"
#include "Npc/TalkNpc.h"
#include "Npc/TalkNpcFreeze.h"
#include "Npc/TokimekiMayorNpc.h"
#include "Npc/VocalMike.h"
#include "Npc/VolleyballNpc.h"
#include "Npc/WorldTravelingNpc.h"
#include "Npc/WorldTravelingPeach.h"
#include "Npc/Yukimaru.h"
#include "Player/Yoshi.h"

const al::NameToCreator<al::ActorCreatorFunction> sProjectActorFactoryEntries[] = {
    {"AchievementNpc", nullptr},
    {"AirBubble", al::createActorFunction<AirBubble>},
    {"AirBubbleGenerator", al::createActorFunction<AirBubbleGenerator>},
    {"AirCurrent", al::createActorFunction<AirCurrent>},
    {"AllDeadWatcher", al::createActorFunction<al::AllDeadWatcher>},
    {"AllDeadWatcherWithShine", al::createActorFunction<AllDeadWatcherWithShine>},
    {"AmiiboHelpNpc", al::createActorFunction<AmiiboHelpNpc>},
    {"AmiiboNpc", al::createActorFunction<AmiiboNpc>},
    {"AnagramAlphabet", al::createActorFunction<AnagramAlphabet>},
#ifdef VER_120
    {"TimeBalloonNpc", nullptr},
#endif
    {"Barrel2D", al::createActorFunction<Barrel2D>},
    {"BarrelGenerator2D", al::createActorFunction<BarrelGenerator2D>},
    {"BarrierField", al::createActorFunction<BarrierField>},
    {"BazookaElectric", al::createActorFunction<BazookaElectric>},
    {"BendLeafTree", al::createActorFunction<BendLeafTree>},
    {"BgmPlayObj", al::createActorFunction<al::BgmPlayObj>},
    {"Bird", al::createActorFunction<Bird>},
    {"BirdCarryMeat", nullptr},
    {"BirdPlayerGlideCtrl", al::createActorFunction<BirdPlayerGlideCtrl>},
    {"BlockBrick", al::createActorFunction<BlockBrick>},
    {"BlockBrick2D", al::createActorFunction<BlockBrick2D>},
    {"BlockBrickBig2D", al::createActorFunction<BlockBrickBig2D>},
    {"BlockEmpty", al::createActorFunction<BlockEmpty>},
    {"BlockEmpty2D", al::createActorFunction<BlockEmpty2D>},
    {"BlockHard", al::createActorFunction<BlockHard>},
    {"ClashWorldBlockHard", al::createActorFunction<BlockHard>},
    {"BlockQuestion", al::createActorFunction<BlockQuestion>},
    {"CityBlockQuestion", al::createActorFunction<BlockQuestion>},
    {"BlockQuestion2D", al::createActorFunction<BlockQuestion2D>},
    {"BlockTransparent", al::createActorFunction<BlockTransparent>},
    {"BlockTransparent2D", al::createActorFunction<BlockTransparent2D>},
    {"BlowObjBeans", al::createActorFunction<BlowObj>},
    {"BlowObjCan", al::createActorFunction<BlowObj>},
    {"BlowObjGarbageBag", al::createActorFunction<BlowObj>},
    {"BlowObjMushroom", al::createActorFunction<BlowObj>},
    {"BlowObj", al::createActorFunction<BlowObj>},
    {"BombTail", al::createActorFunction<BombTail>},
    {"BossForest", al::createActorFunction<BossForest>},
    {"BossForestBlock", al::createActorFunction<BossForestBlock>},
    {"BossForestWander", al::createActorFunction<BossForestWander>},
    {"BossKnuckle", al::createActorFunction<BossKnuckle>},
    {"BossKnuckleCounterGround", al::createActorFunction<BossKnuckleCounterGround>},
    {"BossKnuckleFix", al::createActorFunction<BossKnuckleFix>},
    {"BossMagma", nullptr},
    {"BossRaid", al::createActorFunction<BossRaid>},
    {"BossRaidNpc", al::createActorFunction<BossRaidNpc>},
    {"BossRaidRivet", al::createActorFunction<BossRaidRivet>},
    {"BreakablePole", al::createActorFunction<BreakablePole>},
    {"Breeda", al::createActorFunction<Breeda>},
    {"Bubble", al::createActorFunction<Bubble>},
    {"Bubble2D", nullptr},
    {"BubbleLauncher", al::createActorFunction<BubbleLauncher>},
    {"Bull", nullptr},
    {"Byugo", nullptr},
    {"Cactus", al::createActorFunction<Cactus>},
    {"CactusMini", al::createActorFunction<CactusMini>},
    {"CageShine", al::createActorFunction<CageShineWatcher>},
    {"CageSaveSwitch", al::createActorFunction<CageSwitch>},
    {"CageStageSwitch", al::createActorFunction<CageSwitch>},
    {"CageBreakable", al::createActorFunction<BreakMapParts>},
    {"CameraDemoGateMapParts", al::createActorFunction<CameraDemoGateMapParts>},
    {"CameraDemoKeyMoveMapParts", al::createActorFunction<CameraDemoKeyMoveMapParts>},
    {"CameraRailHolder", al::createActorFunction<al::CameraRailHolder>},
    {"CameraSub", al::createActorFunction<CameraSub>},
    {"CameraWatchPoint", al::createActorFunction<al::CameraWatchPoint>},
    {"Candlestand", al::createActorFunction<Candlestand>},
    {"CandlestandFire", al::createActorFunction<Candlestand>},
    {"CandlestandInitializer", al::createActorFunction<CandlestandInitializer>},
    {"CandlestandBgmDirector", al::createActorFunction<CandlestandBgmDirector>},
    {"CandlestandSaveWatcher", al::createActorFunction<CandlestandSaveWatcher>},
    {"CandlestandWatcher", al::createActorFunction<CandlestandWatcher>},
    {"CapAccelerator", al::createActorFunction<CapAccelerator>},
    {"CapAcceleratorKeyMoveMapParts", al::createActorFunction<CapAccelerator>},
    {"CapAppearMapParts", al::createActorFunction<CapAppearMapParts>},
    {"CapBeamer", al::createActorFunction<CapBeamer>},
    {"CapBomb", al::createActorFunction<CapBomb>},
    {"CapCatapult", al::createActorFunction<CapCatapult>},
    {"CapFlower", al::createActorFunction<CapFlower>},
    {"CapFlowerGroup", al::createActorFunction<CapFlowerGroup>},
    {"CapHanger", al::createActorFunction<CapHanger>},
    {"CapMessageAfterInformation", al::createActorFunction<CapMessageAfterInformation>},
    {"CapRack", al::createActorFunction<CapRack>},
    {"CapRackTimer", al::createActorFunction<CapRack>},
    {"CapRailMover", al::createActorFunction<CapRailMover>},
    {"CapSlotBase", nullptr},
    {"CapSwitch", al::createActorFunction<CapSwitch>},
    {"CapSwitchSave", al::createActorFunction<CapSwitch>},
    {"CapSwitchTimer", al::createActorFunction<CapSwitchTimer>},
    {"CapThrower", al::createActorFunction<CapThrower>},
    {"CapTrampoline", al::createActorFunction<CapTrampoline>},
    {"Car", al::createActorFunction<Car>},
    {"CarSandWorld", al::createActorFunction<Car>},
    {"CarWatcher", al::createActorFunction<CarWatcher>},
    {"CardboardBox", al::createActorFunction<CardboardBox>},
    {"CatchBomb", al::createActorFunction<CatchBomb>},
    {"Chair", al::createActorFunction<Chair>},
    {"CheckpointFlag", al::createActorFunction<CheckpointFlag>},
    {"ChorobonHolder", nullptr},
    {"ChurchDoor", al::createActorFunction<ChurchDoor>},
    {"CityBuilding", al::createActorFunction<CityBuilding>},
    {"CityStreetlight", al::createActorFunction<CityStreetlight>},
    {"CityWorldSign", al::createActorFunction<CityWorldSign>},
    {"CityWorldUndergroundMachine", al::createActorFunction<CityWorldUndergroundMachine>},
    {"CitySign", al::createActorFunction<CitySign>},
    {"CitySignal", al::createActorFunction<CitySignal>},
    {"CityWorldTable", al::createActorFunction<ReactionObject>},
    {"Closet", al::createActorFunction<Closet>},
    {"CloudStep", al::createActorFunction<CloudStep>},
    {"CollapseSandHill", al::createActorFunction<CollapseSandHill>},
    {"CollectAnimalWatcher", al::createActorFunction<CollectAnimalWatcher>},
    {"CollectBgmSpeaker", al::createActorFunction<CollectBgmSpeaker>},
    {"CollectionList", al::createActorFunction<CollectionList>},
    {"Coin", al::createActorFunction<Coin>},
    {"Coin2D", al::createActorFunction<Coin2D>},
    {"Coin2DCityDirector", al::createActorFunction<Coin2DCityDirector>},
    {"CoinBlow", al::createActorFunction<CoinBlow>},
    {"CoinChameleon", al::createActorFunction<CoinChameleon>},
    {"CoinCirclePlacement", al::createActorFunction<CoinCirclePlacement>},
    {"CoinCollect", al::createActorFunction<CoinCollect>},
    {"CoinCollectHintObj", al::createActorFunction<CoinCollectHintObj>},
    {"CoinCollect2D", al::createActorFunction<CoinCollect2D>},
    {"CoinLead", al::createActorFunction<CoinLead>},
    {"CoinRail", al::createActorFunction<CoinRail>},
    {"CoinRing", al::createActorFunction<CoinRing>},
    {"CoinStackGroup", al::createActorFunction<CoinStackGroup>},
    {"CrystalBreakable", al::createActorFunction<CrystalBreakable>},
    {"DamageBallGenerator", al::createActorFunction<DamageBallGenerator>},
    {"DelaySwitch", al::createActorFunction<DelaySwitch>},
    {"DemoActorCapManHero", al::createActorFunction<DemoActorCapManHero>},
    {"DemoActorCapManHeroine", al::createActorFunction<DemoActorCapManHeroine>},
    {"DemoActorKoopaShip", al::createActorFunction<DemoActorKoopaShip>},
    {"DemoActorHack", al::createActorFunction<DemoActorHack>},
    {"DemoActorPeach", al::createActorFunction<DemoActorPeach>},
    {"DemoActorShineTower", al::createActorFunction<DemoActorShineTower>},
    {"DemoPeachWorldHomeWater001", al::createActorFunction<al::RippleFixMapParts>},
    {"DemoChangeEffectObj", al::createActorFunction<DemoChangeEffectObj>},
    {"DemoWorldMoveHomeBackGround", al::createActorFunction<DemoWorldMoveHomeBackGround>},
    {"DemoPeachWedding", al::createActorFunction<DemoPeachWedding>},
    {"DemoPlayer", al::createActorFunction<DemoPlayer>},
    {"DemoPlayerCap", al::createActorFunction<DemoPlayerCap>},
    {"DigPoint", al::createActorFunction<DigPoint>},
    {"DigPointHintPhoto", al::createActorFunction<DigPoint>},
    {"DigPointWater", al::createActorFunction<DigPoint>},
    {"DirectionFixedBillboard", al::createActorFunction<al::FixMapParts>},
    {"Dokan", al::createActorFunction<Dokan>},
    {"DokanKoopa", al::createActorFunction<DokanKoopa>},
    {"DokanMaze", al::createActorFunction<DokanMaze>},
    {"DokanMazeDirector", al::createActorFunction<DokanMazeDirector>},
    {"DokanStageChange", al::createActorFunction<DokanStageChange>},
    {"DonkeyKong2D", al::createActorFunction<DonkeyKong2D>},
    {"Donsuke", nullptr},
    {"Doshi", al::createActorFunction<Doshi>},
    {"DoorAreaChange", al::createActorFunction<DoorAreaChange>},
    {"DoorAreaChangeCap", al::createActorFunction<DoorAreaChangeCap>},
    {"DoorCity", al::createActorFunction<DoorCity>},
    {"DoorSnow", al::createActorFunction<DoorSnow>},
    {"DoorWarp", al::createActorFunction<DoorWarp>},
    {"DoorWarpStageChange", al::createActorFunction<DoorWarpStageChange>},
    {"EchoBlockMapParts", al::createActorFunction<EchoBlockMapParts>},
    {"EffectObj", al::createActorFunction<al::EffectObj>},
    {"EffectObjScale", al::createActorFunction<al::EffectObj>},
    {"EffectObjAlpha", al::createActorFunction<EffectObjAlpha>},
    {"EffectObjCameraEmit", al::createActorFunction<al::EffectObjCameraEmit>},
    {"EffectObjFollowCamera", al::createActorFunction<al::EffectObjFollowCamera>},
    {"EffectObjFollowCameraLimit", al::createActorFunction<al::EffectObjFollowCameraLimit>},
    {"EffectObjInterval", al::createActorFunction<al::EffectObjInterval>},
    {"EffectObjNpcManFar", al::createActorFunction<EffectObjNpcManFar>},
    {"EffectObjQualityChange", al::createActorFunction<EffectObjQualityChange>},
    {"ElectricWire", al::createActorFunction<ElectricWire>},
    {"ElectricWireKoopa", al::createActorFunction<ElectricWireKoopa>},
    {"EntranceCameraStartObj", al::createActorFunction<al::EntranceCameraStartObj>},
    {"EventKeyMoveCameraObjNoDemo", al::createActorFunction<EventKeyMoveCameraObjNoDemo>},
    {"EventKeyMoveCameraObjWithDemo", al::createActorFunction<EventKeyMoveCameraObjWithDemo>},
    {"FigureWalkingNpc", nullptr},
    {"FireBlower", al::createActorFunction<FireBlower>},
    {"FireBrosPossessed", nullptr},
    {"FireSwitch", al::createActorFunction<FireSwitch>},
    {"FireHydrant", al::createActorFunction<FireHydrant>},
    {"FireDrum2D", al::createActorFunction<FireDrum2D>},
    {"FishingFish", al::createActorFunction<FishingFish>},
    {"FixMapParts2D", al::createActorFunction<FixMapParts2D>},
    {"FixMapPartsAppearKillAsync", al::createActorFunction<FixMapPartsAppearKillAsync>},
    {"FixMapPartsBgmChangeAction", al::createActorFunction<FixMapPartsBgmChangeAction>},
    {"FixMapPartsCapHanger", al::createActorFunction<FixMapPartsCapHanger>},
    {"FixMapPartsDitherAppear", al::createActorFunction<FixMapPartsDitherAppear>},
    {"FixMapPartsForceSafetyPoint", al::createActorFunction<FixMapPartsForceSafetyPoint>},
    {"FixMapPartsFukankunZoomCapMessage",
     al::createActorFunction<FixMapPartsFukankunZoomCapMessage>},
    {"FixMapPartsScenarioAction", al::createActorFunction<FixMapPartsScenarioAction>},
    {"FlyObject", al::createActorFunction<FlyObject>},
    {"ForestManSeed", al::createActorFunction<ForestManSeed>},
    {"ForestWorldHomeBreakParts000", al::createActorFunction<BlockHard>},
    {"FogRequester", al::createActorFunction<al::FogRequester>},
    {"FrailBox", al::createActorFunction<FrailBox>},
    {"Frog", al::createActorFunction<Frog>},
    {"Fukankun", al::createActorFunction<Fukankun>},
    {"FukankunZoomCapMessageSun", al::createActorFunction<FukankunZoomCapMessageSun>},
    {"FukuwaraiWatcher", al::createActorFunction<FukuwaraiWatcher>},
    {"ForestWorldEnergyStand", al::createActorFunction<ForestWorldEnergyStand>},
    {"ForestWorldFlowerCtrl", al::createActorFunction<ForestWorldFlowerCtrl>},
    {"GabuZou", nullptr},
    {"GabuZouGroup", nullptr},
    {"Gamane", al::createActorFunction<Gamane>},
    {"GiantWanderBoss", al::createActorFunction<GiantWanderBoss>},
    {"GoalMark", al::createActorFunction<GoalMark>},
    {"GolemClimb", al::createActorFunction<GolemClimb>},
    {"Gotogoton", nullptr},
    {"GotogotonGoal", al::createActorFunction<GotogotonGoal>},
    {"GraphicsObjShadowMaskCube", al::createActorFunction<ProjectGraphicsObjShadowMaskCube>},
    {"GraphicsObjShadowMaskSphere", nullptr},
    {"GrowerBug", nullptr},
    {"GrowerWorm", nullptr},
    {"GrowFlowerCoin", al::createActorFunction<GrowFlowerCoin>},
    {"GrowFlowerWatcher", al::createActorFunction<GrowFlowerWatcher>},
    {"GrowPlantGrowPlace", al::createActorFunction<GrowPlantGrowPlace>},
    {"GrowPlantSeed", nullptr},
    {"GrowPlantStartStage", al::createActorFunction<GrowPlantStartStage>},
    {"GrowPlantWatcher", al::createActorFunction<GrowPlantWatcher>},
    {"Gunetter", al::createActorFunction<GunetterSpin>},
    {"GunetterMove", nullptr},
    {"HackCar", al::createActorFunction<HackCar>},
    {"HackFork", al::createActorFunction<HackFork>},
    {"HammerBrosPossessed", nullptr},
    {"HammerBros2D", al::createActorFunction<HammerBros2D>},
    {"HelpNpc", al::createActorFunction<HelpNpc>},
    {"HintNpc", nullptr},
    {"HintPhoto", al::createActorFunction<HintPhoto>},
    {"HintRouteGuidePoint", nullptr},
    {"HipDropSwitch", al::createActorFunction<HipDropSwitch>},
    {"HipDropSwitchSave", al::createActorFunction<HipDropSwitch>},
    {"HipDropSwitchTimer", al::createActorFunction<HipDropSwitchTimer>},
    {"HipDropTile", al::createActorFunction<HipDropTile>},
    {"HipDropMoveLift", al::createActorFunction<HipDropMoveLift>},
    {"HipDropRepairParts", al::createActorFunction<HipDropRepairParts>},
    {"HipDropTransformPartsWatcher", al::createActorFunction<HipDropTransformPartsWatcher>},
    {"HomeBed", al::createActorFunction<HomeBed>},
    {"HomeChair", al::createActorFunction<HomeChair>},
    {"HomeInside", al::createActorFunction<HomeInside>},
    {"HomeShip", nullptr},
    {"Hosui", al::createActorFunction<Hosui>},
    {"IcicleFall", al::createActorFunction<IcicleFall>},
    {"Imomu", nullptr},
    {"IndicatorDirector", al::createActorFunction<IndicatorDirector>},
    {"Jango", nullptr},
    {"Joku", al::createActorFunction<Joku>},
    {"JugemFishing", al::createActorFunction<JugemFishing>},
    {"JumpingRopeNpc", al::createActorFunction<JumpingRopeNpc>},
    {"Kakku", al::createActorFunction<Kakku>},
    {"KaronWing", al::createActorFunction<KaronWing>},
    {"KeyMoveCameraFix", al::createActorFunction<al::KeyMoveCameraObj>},
    {"KickStone", al::createActorFunction<KickStone>},
    {"KillerLauncher", al::createActorFunction<KillerLauncher>},
    {"KillerLauncherDot", al::createActorFunction<KillerLauncherDot>},
    {"KinokoUfo", al::createActorFunction<KinokoUfo>},
    {"Koopa", al::createActorFunction<Koopa>},
    {"KoopaCapPlayer", al::createActorFunction<KoopaCapPlayer>},
    {"KoopaChurch", al::createActorFunction<KoopaChurch>},
    {"KoopaLv1", al::createActorFunction<KoopaLv1>},
    {"KoopaLv2", al::createActorFunction<KoopaLv1>},
    {"KoopaLv3", al::createActorFunction<KoopaLv1>},
    {"KoopaShip", al::createActorFunction<KoopaShip>},
    {"Kuribo2D3D", al::createActorFunction<Kuribo2D>},
    {"KuriboGenerator2D3D", al::createActorFunction<KuriboGenerator2D>},
    {"KuriboGirl", al::createActorFunction<KuriboGirl>},
    {"KuriboPossessed", al::createActorFunction<KuriboHack>},
    {"KuriboMini", al::createActorFunction<KuriboMini>},
    {"KuriboTowerSwitch", al::createActorFunction<KuriboTowerSwitch>},
    {"KuriboWing", al::createActorFunction<KuriboWing>},
    {"LavaFryingPan", al::createActorFunction<LavaFryingPan>},
    {"LavaStewVeget", al::createActorFunction<LavaStewVeget>},
    {"LavaPan", al::createActorFunction<LavaPan>},
    {"LavaWave", al::createActorFunction<LavaWave>},
    {"LifeMaxUpItem", al::createActorFunction<LifeMaxUpItem>},
    {"LifeMaxUpItem2D", al::createActorFunction<LifeMaxUpItem2D>},
    {"LifeUpItem", al::createActorFunction<LifeUpItem>},
    {"LifeUpItem2D", al::createActorFunction<LifeUpItem2D>},
    {"LightningController", al::createActorFunction<al::LightningController>},
    {"LongGenerator", al::createActorFunction<LongGenerator>},
    {"MarchingCubeBlock", al::createActorFunction<MarchingCubeBlock>},
    {"MapPartsRoulette", al::createActorFunction<MapPartsRoulette>},
    {"Megane", al::createActorFunction<Megane>},
    {"MeganeLiftExLift", al::createActorFunction<MeganeLiftExLift>},
    {"MeganeKeyMoveMapParts", al::createActorFunction<MeganeKeyMoveMapParts>},
    {"MeganeMapParts", al::createActorFunction<MeganeMapParts>},
    {"Mirror", nullptr},
    {"MoonBasementBreakParts", al::createActorFunction<MoonBasementBreakParts>},
    {"MoonBasementClimaxWatcher", nullptr},
    {"MoonBasementFallObj", al::createActorFunction<MoonBasementMeteorPointObj>},
    {"MoonBasementFinalGate", al::createActorFunction<MoonBasementFinalGate>},
    {"MoonBasementFallObjDecoration", al::createActorFunction<MoonBasementFallObjDecoration>},
    {"MoonBasementFloor", al::createActorFunction<MoonBasementFloor>},
    {"MoonBasementGate", nullptr},
    {"MoonBasementMeteorAreaObj", al::createActorFunction<MoonBasementMeteorAreaObj>},
    {"MoonBasementPillar", al::createActorFunction<MoonBasementPillar>},
    {"MoonBasementRock", al::createActorFunction<MoonBasementRock>},
    {"MoonBasementSlideObj", al::createActorFunction<MoonBasementSlideObj>},
    {"MoonRock", al::createActorFunction<MoonRock>},
    {"MoonWorldBell", al::createActorFunction<MoonWorldBell>},
    {"MoonWorldCaptureParadeLift", al::createActorFunction<MoonWorldCaptureParadeLift>},
    {"Mofumofu", al::createActorFunction<Mofumofu>},
    {"MofumofuLv2", al::createActorFunction<Mofumofu>},
    {"MofumofuScrap", al::createActorFunction<MofumofuScrap>},
    {"Motorcycle", al::createActorFunction<Motorcycle>},
    {"MotorcycleParkingLot", al::createActorFunction<MotorcycleParkingLot>},
    {"MoveHomeNpc", al::createActorFunction<MoveHomeNpc>},
    {"MoviePlayerMapParts", al::createActorFunction<MoviePlayerMapParts>},
    {"MultiGateKeeperBonfire", al::createActorFunction<MultiGateKeeperBonfire>},
    {"MultiGateKeeperWatcher", al::createActorFunction<MultiGateKeeperWatcher>},
    {"Mummy", al::createActorFunction<Mummy>},
    {"MummyGenerator", al::createActorFunction<MummyGenerator>},
    {"NeedleTrap", al::createActorFunction<NeedleTrap>},
    {"Nokonoko2D", al::createActorFunction<Nokonoko2D>},
    {"NoteObjFirst", al::createActorFunction<NoteObj>},
    {"NoteObjFirst2D", al::createActorFunction<NoteObj2D>},
    {"NoteObjDirector", al::createActorFunction<NoteObjDirector>},
    {"Objex", al::createActorFunction<Objex>},
    {"OccludedEffectRequester", al::createActorFunction<al::OccludedEffectRequester>},
    {"OceanWave", al::createActorFunction<OceanWaveActor>},
    {"CloudOcean", al::createActorFunction<OceanWaveActor>},
    {"DemoCloudOcean", al::createActorFunction<OceanWaveActor>},
    {"OneMeshFixMapParts", al::createActorFunction<al::OneMeshFixMapParts>},
    {"OpeningStageStartDemo", al::createActorFunction<OpeningStageStartDemo>},
    {"PackunFire", al::createActorFunction<PackunFire>},
    {"PadRumblePoint", al::createActorFunction<PadRumblePoint>},
    {"PaintObj", al::createActorFunction<PaintObj>},
    {"PaulineAtCeremony", al::createActorFunction<PaulineAtCeremony>},
    {"PaulineAudience", al::createActorFunction<PaulineAudience>},
    {"PeachWorldHomeCastleCap", al::createActorFunction<PeachCastleCap>},
    {"PeachWorldGate", al::createActorFunction<PeachWorldGate>},
    {"PeachWorldMoatWater", al::createActorFunction<PeachWorldMoatWater>},
    {"PeachWorldTree", al::createActorFunction<PeachWorldTree>},
    {"Pecho", al::createActorFunction<Pecho>},
    {"Pen", al::createActorFunction<Pen>},
    {"PictureStageChange", al::createActorFunction<PictureStageChange>},
    {"PillarKeyMoveParts", al::createActorFunction<PillarKeyMoveParts>},
    {"PillarSwitchOpenMapParts", al::createActorFunction<PillarSwitchOpenMapParts>},
    {"PlayerMotionObserver", al::createActorFunction<PlayerMotionObserver>},
    {"PlayerStartObj", al::createActorFunction<PlayerStartObj>},
    {"PlayerSubjectiveWatchCheckObj", al::createActorFunction<PlayerSubjectiveWatchCheckObj>},
    {"PlayGuideBoard", al::createActorFunction<PlayGuideBoard>},
    {"PlayRecorder", al::createActorFunction<PlayRecorder>},
    {"PlayerStartObjNoLink", al::createActorFunction<PlayerStartObj>},
    {"PochiHintPhoto", al::createActorFunction<PochiHintPhoto>},
    {"Poetter", al::createActorFunction<Poetter>},
    {"PoleClimbParts", al::createActorFunction<PoleClimbParts>},
    {"PoleClimbPartsBreak", al::createActorFunction<PoleClimbParts>},
    {"PoleGrabCeil", al::createActorFunction<PoleGrabCeil>},
    {"PoleGrabCeilKeyMoveParts", al::createActorFunction<PoleGrabCeil>},
    {"PopnGenerator", al::createActorFunction<PopnGenerator>},
    {"LavaWorldPoster", al::createActorFunction<ReactionObjectPoster>},
    {"PosterCeremony", al::createActorFunction<ReactionObjectPoster>},
    {"PosterWedding", al::createActorFunction<ReactionObjectPoster>},
    {"ReactionObjectSkyRhythm", al::createActorFunction<ReactionObjectSkyRhythm>},
    {"PosterWatcher", al::createActorFunction<PosterWatcher>},
    {"PrePassCausticsLight", nullptr},
    {"PrePassLineLight", nullptr},
    {"PrePassPointLight", nullptr},
    {"PrePassProjLight", nullptr},
    {"PrePassProjOrthoLight", nullptr},
    {"PrePassSpotLight", nullptr},
    {"ProjectRaceCheckPoint", al::createActorFunction<ProjectRaceCheckPoint>},
    {"Pyramid", al::createActorFunction<Pyramid>},
    {"QuestObj", al::createActorFunction<QuestObj>},
    {"RabbitGraph", al::createActorFunction<RabbitGraph>},
    {"RaceAudienceNpc", al::createActorFunction<RaceAudienceNpc>},
    {"RaceManGoal", al::createActorFunction<RaceManGoal>},
    {"RaceManRace", al::createActorFunction<RaceManRace>},
    {"RaceManStart", nullptr},
    {"RaceWatcher", al::createActorFunction<RaceWatcher>},
    {"RadiConRaceWatcher", al::createActorFunction<RadiConRaceWatcher>},
    {"RadioCassette", al::createActorFunction<RadioCassette>},
    {"RadiconNpc", al::createActorFunction<RadiconNpc>},
    {"Radish", al::createActorFunction<Radish>},
    {"RadishGold", al::createActorFunction<Radish>},
    {"RailDrawer", al::createActorFunction<RailDrawer>},
    {"RankingNpc", nullptr},
    {"ReactionObject", al::createActorFunction<ReactionObject>},
    {"CarBreakable", al::createActorFunction<ReactionObjectCarBreakable>},
    {"ReactionObjectDotCharacter", al::createActorFunction<ReactionObject>},
    {"ReflectBombGenerator", al::createActorFunction<ReflectBombGenerator>},
    {"RhythmSpotlight", al::createActorFunction<RhythmSpotlight>},
    {"RippleGeneratePoint", al::createActorFunction<al::RippleGeneratePoint>},
    {"RippleGenerateSquare", al::createActorFunction<al::RippleGeneratePoint>},
    {"RotateTarget", al::createActorFunction<RotateTarget>},
    {"RouletteSwitch", al::createActorFunction<RouletteSwitch>},
    {"RouteGuideArrow", nullptr},
    {"RouteGuideRail", al::createActorFunction<RouteGuideRail>},
    {"RunAwayNpc", al::createActorFunction<RunAwayNpc>},
    {"SandGeyser", al::createActorFunction<SandGeyser>},
    {"SandWorldHomeLift", al::createActorFunction<SandWorldHomeLift>},
    {"SaucePan", al::createActorFunction<SaucePan>},
    {"SaveFlagCheckObj", al::createActorFunction<SaveFlagCheckObj>},
    {"ScenarioStartCameraAnim", al::createActorFunction<ScenarioStartCamera>},
    {"ScenarioStartCameraSimpleZoom", al::createActorFunction<ScenarioStartCamera>},
    {"ScenarioStartCameraRailMove", al::createActorFunction<ScenarioStartCamera>},
    {"Senobi", al::createActorFunction<Senobi>},
    {"SenobiGeneratePoint", al::createActorFunction<SenobiGeneratePoint>},
    {"SenobiMoveMapParts", al::createActorFunction<SenobiMoveMapParts>},
    {"SenobiMoveMapPartsConnector", al::createActorFunction<SenobiMoveMapPartsConnector>},
    {"SeBarrierObj", al::createActorFunction<al::SeBarrierObj>},
    {"SePlayObj", al::createActorFunction<al::SePlayObj>},
    {"SePlayObjWithSave", al::createActorFunction<SePlayObjWithSave>},
    {"SePlayRail", al::createActorFunction<al::SePlayRail>},
    {"SequentialSwitch", al::createActorFunction<SequentialSwitch>},
    {"SessionBgmCtrlObj", nullptr},
    {"SessionMayorNpc", al::createActorFunction<SessionMayorNpc>},
    {"SessionMusicianNpc", nullptr},
    {"Shibaken", al::createActorFunction<Shibaken>},
    {"ShibakenHomeShipInside", al::createActorFunction<Shibaken>},
    {"Shine", al::createActorFunction<Shine>},
    {"ShineWithAppearCamera", al::createActorFunction<Shine>},
    {"ShineChipWatcher", al::createActorFunction<ShineChipWatcher>},
    {"ShineDot", al::createActorFunction<Shine>},
    {"ShineFukankunWatchObj", al::createActorFunction<ShineFukankunWatchObj>},
    {"ShineTowerRocket", al::createActorFunction<ShineTowerRocket>},
    {"ShopBgmPlayer", al::createActorFunction<ShopBgmPlayer>},
    {"ShopMark", al::createActorFunction<ShopMark>},
    {"ShoppingWatcher", nullptr},
    {"SignBoardDanger", al::createActorFunction<SignBoardDanger>},
    {"SignBoardLayoutTexture", al::createActorFunction<SignBoardLayoutTexture>},
    {"SkyFukankunZoomCapMessage", al::createActorFunction<SkyFukankunZoomCapMessage>},
    {"SkyWorldCloud", al::createActorFunction<SkyWorldCloud>},
    {"SkyWorldKoopaFire", al::createActorFunction<SkyWorldKoopaFire>},
    {"SkyWorldKoopaFrame", nullptr},
    {"SkyWorldMiddleViewCloud", al::createActorFunction<SkyWorldMiddleViewCloud>},
    {"SignBoard", al::createActorFunction<SignBoard>},
    {"SnowWorldBigIcicle", al::createActorFunction<SnowWorldBigIcicle>},
    {"SnowWorldSequenceFlagCheckObj", al::createActorFunction<SnowWorldSequenceFlagCheckObj>},
    {"Sky", al::createActorFunction<al::Sky>},
    {"SmallWanderBoss", al::createActorFunction<SmallWanderBoss>},
    {"SneakingMan", al::createActorFunction<SneakingMan>},
    {"SnowManRaceNpc", nullptr},
    {"SnowVolume", al::createActorFunction<SnowVolume>},
    {"SnowVolumeEraser", al::createActorFunction<SnowVolumeEraser>},
    {"Souvenir", al::createActorFunction<Souvenir>},
    {"SouvenirDirector", al::createActorFunction<SouvenirDirector>},
    {"Special2KeyMoveLift", al::createActorFunction<Special2KeyMoveLift>},
    {"Special2KeyMoveParts", al::createActorFunction<Special2KeyMoveParts>},
    {"SphinxQuiz", al::createActorFunction<SphinxQuiz>},
    {"SphinxRide", nullptr},
    {"SphinxTaxiWatcher", al::createActorFunction<SphinxTaxiWatcher>},
    {"Squirrel", al::createActorFunction<Squirrel>},
    {"Stacker", al::createActorFunction<Stacker>},
    {"StackerCapWorldCtrl", al::createActorFunction<StackerCapWorldCtrl>},
    {"StageEventDemo", nullptr},
    {"StageSwitchSelector", al::createActorFunction<StageSwitchSelector>},
    {"StageTalkDemoNpcCap", al::createActorFunction<StageTalkDemoNpcCap>},
    {"StageTalkDemoNpcCapMoonRock", al::createActorFunction<StageTalkDemoNpcCap>},
    {"Stake", al::createActorFunction<Stake>},
    {"Statue", al::createActorFunction<Statue>},
    {"StatueSnapMark", al::createActorFunction<StatueSnapMark>},
    {"SubActorLodFixPartsScenarioAction",
     al::createActorFunction<SubActorLodFixPartsScenarioAction>},
    {"SwitchAnd", al::createActorFunction<SwitchAnd>},
    {"SwitchKeyMoveMapParts", nullptr},
    {"TalkMessageInfoPoint", al::createActorFunction<CapMessagePlacement>},
    {"TalkMessageInfoPointSaveObj", al::createActorFunction<TalkMessageInfoPointSaveObj>},
    {"TalkNpc", al::createActorFunction<TalkNpc>},
    {"TalkNpcFreeze", al::createActorFunction<TalkNpcFreeze>},
    {"TalkNpcCapMan", al::createActorFunction<TalkNpc>},
    {"TalkNpcCapManHero", al::createActorFunction<TalkNpc>},
    {"TalkNpcCityMan", al::createActorFunction<TalkNpc>},
    {"TalkNpcCityManLow", al::createActorFunction<TalkNpc>},
    {"TalkNpcCityManSit", al::createActorFunction<TalkNpc>},
    {"TalkNpcCityMayor", al::createActorFunction<TalkNpc>},
    {"TalkNpcCollectBgm", al::createActorFunction<TalkNpc>},
    {"TalkNpcDesertMan", al::createActorFunction<TalkNpc>},
    {"TalkNpcForestMan", al::createActorFunction<TalkNpc>},
    {"TalkNpcForestManScrap", al::createActorFunction<TalkNpc>},
    {"TalkNpcKinopio", al::createActorFunction<TalkNpc>},
    {"TalkNpcKinopioBrigade", al::createActorFunction<TalkNpc>},
    {"TalkNpcKinopioMember", al::createActorFunction<TalkNpc>},
    {"TalkNpcLakeMan", al::createActorFunction<TalkNpc>},
    {"TalkNpcLavaMan", al::createActorFunction<TalkNpc>},
    {"TalkNpcLavaManCook", al::createActorFunction<TalkNpc>},
    {"TalkNpcLifeUpItemSeller", al::createActorFunction<TalkNpc>},
    {"TalkNpcRabbit", al::createActorFunction<TalkNpc>},
    {"TalkNpcSeaMan", al::createActorFunction<TalkNpc>},
    {"TalkNpcSnowMan", al::createActorFunction<TalkNpc>},
    {"TalkNpcSnowManLeader", al::createActorFunction<TalkNpc>},
    {"TalkNpcSnowManRacer", al::createActorFunction<TalkNpc>},
    {"TalkPoint", al::createActorFunction<TalkPoint>},
    {"Tank", al::createActorFunction<Tank>},
    {"TankReviveCtrl", al::createActorFunction<TankReviveCtrl>},
    {"TaxiStop", nullptr},
    {"TextureReplaceScreen", al::createActorFunction<TextureReplaceScreen>},
    {"ThunderRenderRequester", nullptr},
    {"Togezo", al::createActorFunction<Togezo>},
    {"Togezo2D", al::createActorFunction<Togezo2D>},
    {"TokimekiMayorNpc", al::createActorFunction<TokimekiMayorNpc>},
    {"TrampleBush", al::createActorFunction<TrampleBush>},
    {"TrampleSwitch", al::createActorFunction<TrampleSwitch>},
    {"TrampleSwitchSave", al::createActorFunction<TrampleSwitch>},
    {"TrampleSwitchTimer", al::createActorFunction<TrampleSwitchTimer>},
    {"TransparentWall", al::createActorFunction<TransparentWall>},
    {"TreasureBox", al::createActorFunction<TreasureBox>},
    {"TreasureBoxKey", al::createActorFunction<TreasureBoxKey>},
    {"TreasureBoxSequentialDirector", al::createActorFunction<TreasureBoxSequentialDirector>},
    {"TRex", al::createActorFunction<TRex>},
    {"TRexForceScroll", al::createActorFunction<TRex>},
    {"TRexPatrol", al::createActorFunction<TRex>},
    {"TRexSleep", al::createActorFunction<TRex>},
    {"TRexScrollBreakMapParts", al::createActorFunction<TRexScrollBreakMapParts>},
    {"Tsukkun", nullptr},
    {"TsukkunHole", al::createActorFunction<TsukkunHole>},
    {"TwistChainList", al::createActorFunction<TwistChainList>},
    {"Utsubo", al::createActorFunction<Utsubo>},
    {"UtsuboWatcher", al::createActorFunction<UtsuboWatcher>},
    {"VocalMike", al::createActorFunction<VocalMike>},
    {"VolleyballBase", al::createActorFunction<VolleyballBase>},
    {"VolleyballNet", al::createActorFunction<VolleyballNet>},
    {"VolleyballNpc", al::createActorFunction<VolleyballNpc>},
    {"Wanwan", al::createActorFunction<Wanwan>},
    {"WanwanHole", al::createActorFunction<WanwanHole>},
    {"WaterAreaMoveModel", al::createActorFunction<al::WaterAreaMoveModel>},
    {"WaterfallWorldBigBreakableWall", al::createActorFunction<WaterfallWorldBigBreakableWall>},
    {"WaterfallWorldFallDownBridge", al::createActorFunction<WaterfallWorldFallDownBridge>},
    {"WaterfallWorldHomeCage", al::createActorFunction<WaterfallWorldBigBreakableWall>},
    {"WaterfallWorldWaterfall", al::createActorFunction<WaterfallWorldWaterfall>},
    {"WaterRoad", al::createActorFunction<WaterRoad>},
    {"WeightSwitch", al::createActorFunction<WeightSwitch>},
    {"WheelWaveSurfParts", al::createActorFunction<WheelWaveSurfParts>},
    {"WindBlowPuzzle", al::createActorFunction<WindBlowPuzzle>},
    {"WorldMapEarth", al::createActorFunction<WorldMapEarth>},
    {"WorldTravelingNpc", al::createActorFunction<WorldTravelingNpc>},
    {"WorldTravelingPeach", al::createActorFunction<WorldTravelingPeach>},
    {"WorldWarpHole", al::createActorFunction<WorldWarpHole>},
    {"Fastener", al::createActorFunction<Fastener>},
    {"FastenerObj", al::createActorFunction<FastenerObj>},
    {"AtmosScatterRequester", al::createActorFunction<al::AtmosScatterRequester>},
    {"BackHideParts", al::createActorFunction<al::BackHideParts>},
    {"BreakMapParts", al::createActorFunction<BreakMapParts>},
    {"CapRotateMapParts", al::createActorFunction<CapRotateMapParts>},
    {"ClockMapParts", al::createActorFunction<al::ClockMapParts>},
    {"ConveyerMapParts", al::createActorFunction<al::ConveyerMapParts>},
    {"FallMapParts", al::createActorFunction<al::FallMapParts>},
    {"FixMapParts", al::createActorFunction<al::FixMapParts>},
    {"FloaterMapParts", al::createActorFunction<al::FloaterMapParts>},
    {"FlowMapParts", al::createActorFunction<al::FlowMapParts>},
    {"GateMapParts", al::createActorFunction<al::GateMapParts>},
    {"KeyMoveMapParts", al::createActorFunction<al::KeyMoveMapParts>},
    {"KeyMoveMapPartsGenerator", al::createActorFunction<al::KeyMoveMapPartsGenerator>},
    {"PossessedMapParts", al::createActorFunction<HackMapParts>},
    {"Pukupuku", al::createActorFunction<Pukupuku>},
    {"PulseSwitch", al::createActorFunction<PulseSwitch>},
    {"RailCollision", al::createActorFunction<RailCollision>},
    {"RailMoveMapParts", al::createActorFunction<al::RailMoveMapParts>},
    {"RiseMapParts", al::createActorFunction<RiseMapParts>},
    {"ReactionMapParts", al::createActorFunction<ReactionMapParts>},
    {"RiseMapPartsHolder", al::createActorFunction<RiseMapPartsHolder>},
    {"RocketFlower", al::createActorFunction<RocketFlower>},
    {"RollingCubeMapParts", al::createActorFunction<al::RollingCubeMapParts>},
    {"RippleFixMapParts", al::createActorFunction<al::RippleFixMapParts>},
    {"RotateMapParts", al::createActorFunction<al::RotateMapParts>},
    {"SeesawMapParts", al::createActorFunction<al::SeesawMapParts>},
    {"SlideMapParts", al::createActorFunction<al::SlideMapParts>},
    {"SubActorLodMapParts", al::createActorFunction<al::SubActorLodMapParts>},
    {"SurfMapParts", al::createActorFunction<al::SurfMapParts>},
    {"SwingMapParts", al::createActorFunction<al::SwingMapParts>},
    {"SwitchDitherMapParts", al::createActorFunction<al::SwitchDitherMapParts>},
    {"SwitchKeepOnWatcher", al::createActorFunction<al::SwitchKeepOnWatcher>},
    {"SwitchOpenMapParts", al::createActorFunction<al::SwitchOpenMapParts>},
    {"VisibleSwitchMapParts", al::createActorFunction<al::VisibleSwitchMapParts>},
    {"WaveSurfMapParts", al::createActorFunction<WaveSurfMapParts>},
    {"WheelMapParts", al::createActorFunction<al::WheelMapParts>},
    {"WobbleMapParts", al::createActorFunction<al::WobbleMapParts>},
    {"WindBlowMapParts", al::createActorFunction<WindBlowMapParts>},
    {"Yoshi", al::createActorFunction<Yoshi>},
    {"YoshiFruit", al::createActorFunction<YoshiFruit>},
    {"YoshiFruitShineHolder", al::createActorFunction<YoshiFruitShineHolder>},
    {"Yukimaru", al::createActorFunction<Yukimaru>},
    {"YukimaruRacer", nullptr},
    {"YukimaruRacerTiago", nullptr}};

ProjectActorFactory::ProjectActorFactory() : ActorFactory("アクター生成") {  //("繧｢繧ｯ繧ｿ繝ｼ逕滓")
    initFactory(sProjectActorFactoryEntries);
}
